---
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "984"
    networks:
      - jenkins-net

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - jenkins-net

volumes:
  jenkins-data:
    name: jenkins-101_jenkins-data  # <-- The exact name of your old volume
    external: true  
  nexus-data:

networks:
  jenkins-net:
    driver: bridge