---
services:
  mysql:
    image: mysql
    container_name: petclinic-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - petclinic-net

  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-petclinic
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    ports:
      - "9090:8080"
    networks:
      - petclinic-net

volumes:
  mysql_data:

networks:
  petclinic-net:
    driver: bridge
