apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  strategy: {}
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        - name: SPRING_APPLICATION_JSON
          value: |
            {
              "management.endpoint.health.probes.enabled": true,
              "management.endpoint.health.probes.add-additional-paths": true,
              "management.endpoints.web.exposure.include": "health,info"
            }
        image: ghcr.io/abdullah-hamada7/spring-petclinic-repo/spring-petclinic:1ddd28d1cdf876d244acccbfcf5f9f69f52208de
        name: app
        ports:
        - containerPort: 8080
          name: http
        resources: {}
        volumeMounts:
        - mountPath: /bindings/secret
          name: binding
          readOnly: true
      volumes:
      - name: binding
        projected:
          sources:
          - secret:
              name: sec-mysql
status: {}
