apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z mysql 3306; do echo "waiting for mysql"; sleep 5; done;
      containers:
        - name: app
          image: docker.io/abdullahhamada7/spring-petclinic:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
          ports:
            - containerPort: 8080