name: Build, Deploy and Test Petclinic on Minikube

on:
  push:
    branches: [main]
    paths:
      - 'k8s/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven Wrapper
        run: ./mvnw -B verify -DskipTests

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/spring-petclinic:${{ github.sha }}"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update K8s manifest
        run: |
          sudo snap install yq
          yq e -i '.spec.template.spec.containers[0].image = strenv(IMAGE)' k8s/petclinic.yml

      - name: Commit and push manifest update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8s/petclinic.yml
          git commit -m "chore: update petclinic image to $IMAGE" || echo "No changes to commit"
          git push

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/db_mysql.yml
          kubectl apply -f k8s/petclinic.yml

      - name: Wait for Pods
        run: |
          kubectl wait --for=condition=ready pod -l app=demo-db --timeout=180s
          kubectl wait --for=condition=ready pod -l app=petclinic --timeout=180s